version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gradecalculator"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1w67eui2xkqhf"
s3_prefix = "gradecalculator"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
